### PR TITLE
v0.15

### PR DESCRIPTION
**Pull request by ismaelestalayo**
- Moved "All Software" button from the end of the Home page to the bottom bar
- Added "Favorites" to the bottom bar
- Added quick "Fav" toggle button to the Y button
- Added "Number of recent games" to the Settings

Screenshots would need to be updated to show the new changes

### CODE REVIEW

**Review by RBertoCases — COMMENTED** [review]
I don't think I want the All Software button moved. I'd like to keep the UX close to what's on Switch. But I'm giving the change a test drive to see how I like it.

**Comment by ismaelestalayo** [comment]
I understand. I dont have a Switch, so I'm not doing a 1:1 look.
However I was actually thinking of closing this PR as I've been adding way more changes (not still commited) like a Systems view (similar to switchOS).

So maybe the best thing is to close this PR without merging, and you can then cherry pick any changes from my fork (like the Fav toggle and section). What do you think?

**Comment by ismaelestalayo** [comment]
This is how it currently looks my local work-in-progress. I added a setting to choose between the home view being your Recents view, or my Systems view.

image

**Comment by ismaelestalayo** [comment]
I'm closing this PR as I'm commiting a few big changes to my fork. 
However as I said, feel free to bring any of my changes to your repo

**Comment by RBertoCases** [comment]
That sounds good. I like a lot of your changes and I'll be bringing them into my repo, especially your work on favorites.

Thank you!

**Pull request closed without merging**
